name: Linter
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: GitHub Action for pylint
      uses: cclauss/GitHub-Action-for-pylint@0.7.0

